# -*- coding: utf-8 -*-
"""project_euler_02

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CRooRRV5VWfPe6dygz031f_SuEllye7H
"""

import numpy as np

f = []
f.append(1)
f.append(2)

i=1
while f[i] < 4000000:
  f1 = f[i-1]+f[i]
  f.append(f1)
  i += 1
if f[-1]>4000000:
  del f[-1]


sum = 0
for i in f:
  if i%2==0:
    sum += i

print(sum)

f[-1]

